Description: >
     ECS cluster and ECS Task Execution IAM Role
Parameters:

    EnvironmentName:
        Type: String

    VPC:
        Type: AWS::EC2::VPC::Id

Resources:

    ECSCluster:
        Type: AWS::ECS::Cluster
        Properties:
            ClusterName: !Ref EnvironmentName

    ECSTaskExecutionRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                - Effect: Allow
                  Principal:
                    Service: [ecs-tasks.amazonaws.com]
                  Action: ['sts:AssumeRole']
            Path: /
            Policies:
                - PolicyName: AmazonECSTaskExecutionRolePolicy
                  PolicyDocument:
                    Statement:
                    - Effect: Allow
                      Action:
                        - 'ecr:GetAuthorizationToken'
                        - 'ecr:BatchCheckLayerAvailability'
                        - 'ecr:GetDownloadUrlForLayer'
                        - 'ecr:BatchGetImage'

                        - 'logs:CreateLogStream'
                        - 'logs:PutLogEvents'
                      Resource: '*'

Outputs:

    Cluster:
        Value: !Ref ECSCluster

    ECSTaskExecutionRole:
        Value: !GetAtt ECSTaskExecutionRole.Arn
