Description: >
    Application Load Balancer to public subnets

Parameters:

    EnvironmentName:
        Type: String

    SecurityGroup:
        Type: AWS::EC2::SecurityGroup::Id

    Subnets:
        Type: List<AWS::EC2::Subnet::Id>

    VPC:
        Type: AWS::EC2::VPC::Id

Resources:

    LoadBalancer:
        Type: AWS::ElasticLoadBalancingV2::LoadBalancer
        Properties:
            Name: !Ref EnvironmentName
            Subnets: !Ref Subnets
            SecurityGroups: 
                - !Ref SecurityGroup
            Tags: 
                - Key: Name
                  Value: !Ref EnvironmentName

    LoadBalancerListener:
        Type: AWS::ElasticLoadBalancingV2::Listener
        Properties:
            LoadBalancerArn: !Ref LoadBalancer
            Port: 80
            Protocol: HTTP 
            DefaultActions: 
                - Type: forward
                  TargetGroupArn: !Ref DefaultTargetGroup
    
    DefaultTargetGroup:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            Name: !Sub ${EnvironmentName}-default
            VpcId: !Ref VPC
            Port: 80
            Protocol: HTTP
            TargetType: ip
           
Outputs:

    Listener:
        Value: !Ref LoadBalancerListener  

    LoadBalancer:
        Value: !Ref LoadBalancer

    LoadBalancerUrl:
        Value: !GetAtt LoadBalancer.DNSName
