Description: >
    VPC with public and private subnets across 2 AZ with an Internet Gateway and pair of NAT
    Gateways, deploys an ECS cluster distributed across multiple AZ and ECS services from ECR
    Last Modified: 8th February 2019
    Author: Pradeep T <pradeep.t@infosys.com>
Resources:
    VPC:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3-us-west-1.amazonaws.com/wm-ui-app/CFT/vpc.yaml
            Parameters:
                EnvironmentName:    !Ref AWS::StackName
                PrivateSubnet1CIDR: 10.0.21.0/24
                PrivateSubnet2CIDR: 10.0.22.0/24
                PublicSubnet1CIDR:  10.0.23.0/24
                PublicSubnet2CIDR:  10.0.24.0/24
                VpcCIDR:            10.0.0.0/16

    SecurityGroups:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3-us-west-1.amazonaws.com/wm-ui-app/CFT/sg.yaml
            Parameters: 
                EnvironmentName: !Ref AWS::StackName
                VPC: !GetAtt VPC.Outputs.VPC

    ALB:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3-us-west-1.amazonaws.com/wm-ui-app/CFT/lb.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                SecurityGroup: !GetAtt SecurityGroups.Outputs.LoadBalancerSecurityGroup
                Subnets: !GetAtt VPC.Outputs.PublicSubnets
                VPC: !GetAtt VPC.Outputs.VPC

    ECS:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3-us-west-1.amazonaws.com/wm-ui-app/CFT/cluster.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                VPC: !GetAtt VPC.Outputs.VPC

    ProductService:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3-us-west-1.amazonaws.com/wm-ui-app/CFT/productservice.yaml
            Parameters:
                Cluster: !GetAtt ECS.Outputs.Cluster
                DesiredCount: 2
                ECSTaskExecutionRole: !GetAtt ECS.Outputs.ECSTaskExecutionRole
                Listener: !GetAtt ALB.Outputs.Listener 
                Path: /product
                SecurityGroup: !GetAtt SecurityGroups.Outputs.ECSHostSecurityGroup
                Subnets: !GetAtt VPC.Outputs.PrivateSubnets
                TaskCpu: 256
                TaskMemory: 512
                VPC: !GetAtt VPC.Outputs.VPC

    ContentService:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3-us-west-1.amazonaws.com/wm-ui-app/CFT/contentservice.yaml
            Parameters:
                Cluster: !GetAtt ECS.Outputs.Cluster
                DesiredCount: 2
                ECSTaskExecutionRole: !GetAtt ECS.Outputs.ECSTaskExecutionRole
                Listener: !GetAtt ALB.Outputs.Listener 
                Path: /content
                SecurityGroup: !GetAtt SecurityGroups.Outputs.ECSHostSecurityGroup
                Subnets: !GetAtt VPC.Outputs.PrivateSubnets
                TaskCpu: 256
                TaskMemory: 512
                VPC: !GetAtt VPC.Outputs.VPC

    CategoryService:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3-us-west-1.amazonaws.com/wm-ui-app/CFT/categoryservice.yaml
            Parameters:
                Cluster: !GetAtt ECS.Outputs.Cluster
                DesiredCount: 2
                ECSTaskExecutionRole: !GetAtt ECS.Outputs.ECSTaskExecutionRole
                Listener: !GetAtt ALB.Outputs.Listener 
                Path: /category
                SecurityGroup: !GetAtt SecurityGroups.Outputs.ECSHostSecurityGroup
                Subnets: !GetAtt VPC.Outputs.PrivateSubnets
                TaskCpu: 256
                TaskMemory: 512
                VPC: !GetAtt VPC.Outputs.VPC

    SearchService:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3-us-west-1.amazonaws.com/wm-ui-app/CFT/searchservice.yaml
            Parameters:
                Cluster: !GetAtt ECS.Outputs.Cluster
                DesiredCount: 2
                ECSTaskExecutionRole: !GetAtt ECS.Outputs.ECSTaskExecutionRole
                Listener: !GetAtt ALB.Outputs.Listener 
                Path: /search
                SecurityGroup: !GetAtt SecurityGroups.Outputs.ECSHostSecurityGroup
                Subnets: !GetAtt VPC.Outputs.PrivateSubnets
                TaskCpu: 256
                TaskMemory: 512
                VPC: !GetAtt VPC.Outputs.VPC

    WebsiteService:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3-us-west-1.amazonaws.com/wm-ui-app/CFT/websiteservice.yaml
            Parameters:
                Cluster: !GetAtt ECS.Outputs.Cluster
                DesiredCount: 2
                ECSTaskExecutionRole: !GetAtt ECS.Outputs.ECSTaskExecutionRole
                Listener: !GetAtt ALB.Outputs.Listener 
                Path: /
                ProductServiceUrl: !Join [ "/", [ !GetAtt ALB.Outputs.LoadBalancerUrl, "product" ]]
                ContentServiceUrl: !Join [ "/", [ !GetAtt ALB.Outputs.LoadBalancerUrl, "content" ]]
                CategoryServiceUrl: !Join [ "/", [ !GetAtt ALB.Outputs.LoadBalancerUrl, "category" ]]
                SearchServiceUrl: !Join [ "/", [ !GetAtt ALB.Outputs.LoadBalancerUrl, "search" ]]
                SecurityGroup: !GetAtt SecurityGroups.Outputs.ECSHostSecurityGroup
                Subnets: !GetAtt VPC.Outputs.PrivateSubnets
                TaskCpu: 256
                TaskMemory: 512
                VPC: !GetAtt VPC.Outputs.VPC

Outputs:

    ProductServiceUrl: 
        Description: The URL endpoint for the product service
        Value: !Join [ "/", [ !GetAtt ALB.Outputs.LoadBalancerUrl, "product" ]]

    ContentServiceUrl: 
        Description: The URL endpoint for the product service
        Value: !Join [ "/", [ !GetAtt ALB.Outputs.LoadBalancerUrl, "content" ]]

    CategoryServiceUrl: 
        Description: The URL endpoint for the product service
        Value: !Join [ "/", [ !GetAtt ALB.Outputs.LoadBalancerUrl, "category" ]]

    SearchServiceUrl: 
        Description: The URL endpoint for the product service
        Value: !Join [ "/", [ !GetAtt ALB.Outputs.LoadBalancerUrl, "search" ]]

    WebsiteServiceUrl: 
        Description: The URL endpoint for the website service
        Value: !Join ["", [ !GetAtt ALB.Outputs.LoadBalancerUrl, "/" ]]
