Description: >
    ECS Category service-JSON API of products.
Parameters: 
    Cluster:
        Type: String

    DesiredCount: 
        Type: Number

    ECSTaskExecutionRole:
        Type: String

    Listener:
        Type: String

    Path: 
        Type: String

    SecurityGroup:
        Type: AWS::EC2::SecurityGroup::Id

    Subnets:
        Type: List<AWS::EC2::Subnet::Id>

    TaskCpu:
        Type: Number

    TaskMemory:
        Type: Number

    VPC:
        Type: AWS::EC2::VPC::Id
        
Resources:

    Service: 
        Type: AWS::ECS::Service
        DependsOn: ListenerRule
        Properties: 
            Cluster: !Ref Cluster
            DeploymentConfiguration:
                MaximumPercent: 200
                MinimumHealthyPercent: 75
            DesiredCount: !Ref DesiredCount
            LaunchType: FARGATE
            NetworkConfiguration:
                AwsvpcConfiguration:
                    AssignPublicIp: ENABLED
                    SecurityGroups:
                      - !Ref SecurityGroup
                    Subnets:
                      - !Select [ 0, !Ref Subnets ]
                      - !Select [ 1, !Ref Subnets ]
            TaskDefinition: !Ref TaskDefinition
            LoadBalancers: 
                - ContainerName: "searchservice"
                  ContainerPort: 8003
                  TargetGroupArn: !Ref TargetGroup

    TaskDefinition:
        Type: AWS::ECS::TaskDefinition
        Properties:
            Family: searchservice
            Cpu: !Ref 'TaskCpu'
            Memory: !Ref 'TaskMemory'
            NetworkMode: awsvpc
            RequiresCompatibilities:
              - FARGATE
            ExecutionRoleArn: !Ref ECSTaskExecutionRole
            ContainerDefinitions:
                - Name: searchservice
                  Essential: true
                  Image: 666303174975.dkr.ecr.us-west-1.amazonaws.com/wm-api-category:latest
                  Cpu: 256
                  Memory: 512
                  PortMappings:
                    - ContainerPort: 8003
                  LogConfiguration:
                    LogDriver: awslogs
                    Options:
                        awslogs-group: '/ecs/apisearch'
                        awslogs-region: 'us-west-1'
                        awslogs-stream-prefix: 'ecs'
    
    CloudWatchLogsGroup:
        Type: AWS::Logs::LogGroup
        Properties: 
            LogGroupName: !Ref AWS::StackName
            RetentionInDays: 5  

    TargetGroup:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            VpcId: !Ref VPC
            Port: 80
            Protocol: HTTP
            TargetType: ip
            Matcher: 
                HttpCode: 200-299
            HealthCheckIntervalSeconds: 10
            HealthCheckPath: /search
            HealthCheckProtocol: HTTP
            HealthCheckTimeoutSeconds: 5
            HealthyThresholdCount: 2
    
    ListenerRule:
        Type: AWS::ElasticLoadBalancingV2::ListenerRule
        Properties:
            ListenerArn: !Ref Listener
            Priority: 5
            Conditions:
                - Field: path-pattern
                  Values: 
                    - !Ref Path
            Actions:
                - TargetGroupArn: !Ref TargetGroup
                  Type: forward
