AWSTemplateFormatVersion: '2010-09-09'
Description: An internal service discovery namespace
Parameters:
  EnvironmentName:
    Type: String
    Default: demo
    Description: The name of the environment to add this service discovery namespace to
  Domain:
    Type: String
    Default: service.demo
Resources:
  EcsSecurityGroupIngressFromSelf:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Ingress from other containers in the cluster
      GroupId:
        Fn::ImportValue: !Sub ${EnvironmentName}:ContainerSecurityGroup
      IpProtocol: -1
      SourceSecurityGroupId:
        Fn::ImportValue: !Sub ${EnvironmentName}:ContainerSecurityGroup

  ServiceDiscoveryNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Name: !Ref Domain
      Vpc:
        Fn::ImportValue: !Sub ${EnvironmentName}:VpcId

Outputs:
  PrivateServiceDiscoveryNamespace:
    Description: The ID of the private service discovery namespace
    Value: !Ref ServiceDiscoveryNamespace
    Export:
      Name: !Sub ${EnvironmentName}:PrivateServiceDiscoveryNamespace

