Description: >
    security groups required by entire stack
Parameters:
    
    EnvironmentName:
        Type: String
        Default: "Env"
    
    VPC:
        Type: AWS::EC2::VPC::Id

Resources:

    ECSHostSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties: 
            VpcId: !ImportValue VPC
            GroupDescription: Access to tasks/containers that run on ECS cluster
            SecurityGroupIngress:
                - SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup 
                  IpProtocol: -1
            Tags: 
                - Key: Name
                  Value: !Sub ${EnvironmentName}-ECS-Hosts

    LoadBalancerSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties: 
            VpcId: !ImportValue VPC
            GroupDescription: Access to the load balancer in front of  ECS cluster
            SecurityGroupIngress:
                - CidrIp: 0.0.0.0/0
                  IpProtocol: -1
            Tags: 
                - Key: Name
                  Value: !Sub ${EnvironmentName}-LoadBalancers

Outputs:

    ECSHostSecurityGroup: 
        Value: !Ref ECSHostSecurityGroup
        Export:
          Name: 'ECSHostSecurityGroup'

    LoadBalancerSecurityGroup:
        Value: !Ref LoadBalancerSecurityGroup
        Export:
          Name: 'LoadBalancerSecurityGroup'
