Description:
    ECS service connecting to another ECS service (product)

Parameters: 

    Cluster:
        Type: String

    DesiredCount: 
        Type: Number
        Default: 2

    ECSTaskExecutionRole:
        Type: String

    Listener:
        Type: String

    Path: 
        Type: String
        Default: /

    ProductServiceUrl:
        Type: String
    ContentServiceUrl:
        Type: String
    CategoryServiceUrl:
        Type: String
    SearchServiceUrl:
        Type: String

    SecurityGroup:
        Type: AWS::EC2::SecurityGroup::Id

    Subnets:
        Type: List<AWS::EC2::Subnet::Id>

    TaskCpu:
        Default: 256
        Type: Number

    TaskMemory:
        Default: 512
        Type: Number

    VPC:
        Type: AWS::EC2::VPC::Id
        
Resources:

    Service: 
        Type: AWS::ECS::Service
        DependsOn: ListenerRule
        Properties: 
            Cluster: !Ref Cluster
            DeploymentConfiguration:
                MaximumPercent: 200
                MinimumHealthyPercent: 75
            DesiredCount: !Ref DesiredCount
            LaunchType: FARGATE
            NetworkConfiguration:
                AwsvpcConfiguration:
                    AssignPublicIp: ENABLED
                    SecurityGroups:
                      - !Ref SecurityGroup
                    Subnets:
                      - !Select [ 0, !Ref Subnets ]
                      - !Select [ 1, !Ref Subnets ]
            TaskDefinition: !Ref TaskDefinition
            LoadBalancers: 
                - ContainerName: "website"
                  ContainerPort: 80
                  TargetGroupArn: !Ref TargetGroup

    TaskDefinition:
        Type: AWS::ECS::TaskDefinition
        Properties:
            Family: website
            Cpu: !Ref 'TaskCpu'
            Memory: !Ref 'TaskMemory'
            NetworkMode: awsvpc
            RequiresCompatibilities:
              - FARGATE
            ExecutionRoleArn: !Ref ECSTaskExecutionRole
            ContainerDefinitions:
                - Name: website
                  Essential: true
                  Image: 666303174975.dkr.ecr.us-west-1.amazonaws.com/wm-api-test:latest
                  Cpu: 256
                  Memory: 512
                  MemoryReservation: 256
                  Environment: 
                    - Name: PRODUCT_SERVICE_URL
                      Value: !Ref ProductServiceUrl
                    - Name: CONTENT_SERVICE_URL
                      Value: !Ref ContentServiceUrl
                    - Name: CATEGORY_SERVICE_URL
                      Value: !Ref CategoryServiceUrl
                    - Name: SEARCH_SERVICE_URL
                      Value: !Ref SearchServiceUrl
                  PortMappings:
                    - ContainerPort: 80

    CloudWatchLogsGroup:
        Type: AWS::Logs::LogGroup
        Properties: 
            LogGroupName: !Ref AWS::StackName
            RetentionInDays: 5  

    TargetGroup:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            VpcId: !Ref VPC
            Port: 80
            Protocol: HTTP
            TargetType: ip
            Matcher: 
                HttpCode: 200-299
            HealthCheckIntervalSeconds: 10
            HealthCheckPath: /
            HealthCheckProtocol: HTTP
            HealthCheckTimeoutSeconds: 5
            HealthyThresholdCount: 2
    
    ListenerRule:
        Type: AWS::ElasticLoadBalancingV2::ListenerRule
        Properties:
            ListenerArn: !Ref Listener
            Priority: 1
            Conditions:
                - Field: path-pattern
                  Values: 
                    - !Ref Path
            Actions:
                - TargetGroupArn: !Ref TargetGroup
                  Type: forward
